# config/strategies/crypto_strategy.yaml
strategy:
  name: "Multi-Timeframe Quantum Strategy"
  version: "2.1"
  author: "DeepSeek Trading"
  base_currency: "USDT"
  assets: ["BTC", "ETH", "SOL", "XRP", "DOGE", "LTC"]

indicators:
  trend:
    ema_periods: [8, 13, 21, 34, 55]
    macd:
      fast_period: 12
      slow_period: 26
      signal_period: 9
    ichimoku:
      conversion_period: 9
      base_period: 26
      lagging_span: 52
      displacement: 26

  momentum:
    rsi_period: 14
    stoch_period: 14
    stoch_smooth: 3
    cci_period: 20

  volatility:
    atr_period: 14
    bollinger_period: 20
    bollinger_std: 2
    keltner_period: 20
    keltner_multiplier: 1.5

  volume:
    vwap_period: 20
    obv_period: 14
    volume_spike_threshold: 1.8

signals:
  buy_conditions:
    primary:
      - "ema_8 > ema_21"
      - "macd_hist > 0"
      - "rsi > 55"
      - "close > vwap"
    secondary:
      - "volume > sma_volume_20 * 1.5"
      - "stoch_k > stoch_d"
      - "atr > sma_atr_14"

  sell_conditions:
    primary:
      - "ema_8 < ema_21"
      - "macd_hist < 0"
      - "rsi < 45"
      - "close < vwap"
    secondary:
      - "volume > sma_volume_20 * 1.2"
      - "stoch_k < stoch_d"
      - "atr < sma_atr_14"

risk_management:
  position_sizing:
    max_portfolio_risk: 2.0  # Percentage
    volatility_adjusted: true
    kelly_criterion: true

  stop_loss:
    atr_multiplier: 2.0
    support_resistance_buffer: 1.5  # Percentage

  take_profit:
    risk_reward_ratio: 3:1
    fibonacci_levels: [1.272, 1.618, 2.0]

alerts:
  confidence_threshold: 0.85
  timeframe_alignment: ["4h", "1h", "15m", "5m"]
  notification_channels: ["telegram", "email"]
  cooldown_period: 300  # Seconds

model:
  training:
    retrain_interval: 24  # Hours
    lookback_window: 365  # Days
    feature_engineering:
      lag_features: [1, 3, 5, 7]
      rolling_windows: [7, 14, 21]
      volatility_features: true
      pattern_recognition: true

  hyperparameters:
    xgboost:
      n_estimators: 500
      max_depth: 6
      learning_rate: 0.01
      subsample: 0.8
      colsample_bytree: 0.8
